"""add tool_authorization_attempts

Revision ID: 0e3c98acf69d
Revises: 4378ec26485b
Create Date: 2026-05-13 09:09:38.916535

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0e3c98acf69d'
down_revision: str | Sequence[str] | None = '4378ec26485b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_authorization_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('agent_instance_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=1024), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('matched_rule', sa.String(length=255), nullable=True),
    sa.Column('suggestion', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_instance_id'], ['agent_instances.id'], name=op.f('fk_tool_authorization_attempts_agent_instance_id_agent_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_tool_authorization_attempts_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_tool_authorization_attempts_squad_id_squads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_tool_authorization_attempts_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_authorization_attempts'))
    )
    op.create_index(op.f('ix_tool_authorization_attempts_allowed'), 'tool_authorization_attempts', ['allowed'], unique=False)
    op.create_index(op.f('ix_tool_authorization_attempts_client_id'), 'tool_authorization_attempts', ['client_id'], unique=False)
    op.create_index(op.f('ix_tool_authorization_attempts_squad_id'), 'tool_authorization_attempts', ['squad_id'], unique=False)
    op.create_index(op.f('ix_tool_authorization_attempts_task_id'), 'tool_authorization_attempts', ['task_id'], unique=False)
    op.create_index(op.f('ix_tool_authorization_attempts_tool_name'), 'tool_authorization_attempts', ['tool_name'], unique=False)
    op.alter_column('billing_periods', 'total_cost_direct_usd',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               server_default=None,
               existing_nullable=False)
    op.alter_column('billing_periods', 'total_cost_direct_brl',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('billing_periods', 'total_cost_infra_brl',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('billing_periods', 'total_cost_fixed_brl',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('billing_periods', 'total_cost_full_brl',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('client_billing_plans', 'infra_overhead_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('client_billing_plans', 'fixed_overhead_brl_per_task',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('client_billing_plans', 'usd_to_brl_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_billing_plans', 'usd_to_brl_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               server_default=sa.text('5.0'),
               existing_nullable=False)
    op.alter_column('client_billing_plans', 'fixed_overhead_brl_per_task',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('client_billing_plans', 'infra_overhead_pct',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=sa.text("'20'::numeric"),
               existing_nullable=False)
    op.alter_column('billing_periods', 'total_cost_full_brl',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('billing_periods', 'total_cost_fixed_brl',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('billing_periods', 'total_cost_infra_brl',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('billing_periods', 'total_cost_direct_brl',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('billing_periods', 'total_cost_direct_usd',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.drop_index(op.f('ix_tool_authorization_attempts_tool_name'), table_name='tool_authorization_attempts')
    op.drop_index(op.f('ix_tool_authorization_attempts_task_id'), table_name='tool_authorization_attempts')
    op.drop_index(op.f('ix_tool_authorization_attempts_squad_id'), table_name='tool_authorization_attempts')
    op.drop_index(op.f('ix_tool_authorization_attempts_client_id'), table_name='tool_authorization_attempts')
    op.drop_index(op.f('ix_tool_authorization_attempts_allowed'), table_name='tool_authorization_attempts')
    op.drop_table('tool_authorization_attempts')
    # ### end Alembic commands ###
