"""initial schema

Revision ID: 188ba8eb067d
Revises: 
Create Date: 2026-05-12 15:48:29.577925

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '188ba8eb067d'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('jira_workspace_url', sa.String(length=255), nullable=True),
    sa.Column('jira_email', sa.String(length=255), nullable=True),
    sa.Column('jira_credential_id', sa.UUID(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jira_credential_id'], ['encrypted_secrets.id'], name='fk_clients_jira_credential_id_encrypted_secrets', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_index(op.f('ix_clients_slug'), 'clients', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_system_admin', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('billing_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_tokens_input', sa.Integer(), nullable=False),
    sa.Column('total_tokens_output', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('total_tasks_closed', sa.Integer(), nullable=False),
    sa.Column('base_fee_amount_brl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overage_amount_brl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('invoice_amount_brl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('invoice_status', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_billing_periods_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_periods'))
    )
    op.create_index(op.f('ix_billing_periods_client_id'), 'billing_periods', ['client_id'], unique=False)
    op.create_table('client_billing_plans',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('plan_kind', sa.Enum('FIXED', 'PAY_PER_USE', 'HYBRID', name='billing_plan_kind_enum'), nullable=False),
    sa.Column('base_fee_monthly_brl', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('included_quota_tokens', sa.BigInteger(), nullable=False),
    sa.Column('included_quota_tasks', sa.Integer(), nullable=False),
    sa.Column('overage_markup_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_billing_plans_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', name=op.f('pk_client_billing_plans'))
    )
    op.create_table('client_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM_ADMIN', 'CLIENT_ADMIN', 'CLIENT_REVIEWER', 'CLIENT_VIEWER', name='user_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_memberships_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_client_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_memberships')),
    sa.UniqueConstraint('client_id', 'user_id', name='uq_client_user')
    )
    op.create_index(op.f('ix_client_memberships_client_id'), 'client_memberships', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_memberships_user_id'), 'client_memberships', ['user_id'], unique=False)
    op.create_table('encrypted_secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('GITHUB_TOKEN', 'GITLAB_TOKEN', 'JIRA_TOKEN', 'GENERIC', name='secret_kind_enum'), nullable=False),
    sa.Column('encrypted_value', sa.LargeBinary(), nullable=False),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_encrypted_secrets_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encrypted_secrets'))
    )
    op.create_index(op.f('ix_encrypted_secrets_client_id'), 'encrypted_secrets', ['client_id'], unique=False)
    op.create_table('skill_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('BA', 'ARCHITECT', 'DEV', 'ONBOARDING_ANALYST', name='agent_tier_enum'), nullable=False),
    sa.Column('model_alias', sa.String(length=64), nullable=False),
    sa.Column('stack_primary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stack_secondary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('system_prompt_ref', sa.String(length=512), nullable=False),
    sa.Column('tools_enabled', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('knowledge_partitions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_skill_templates_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_templates')),
    sa.UniqueConstraint('client_id', 'slug', 'version', name='uq_skill_slug_version')
    )
    op.create_index(op.f('ix_skill_templates_client_id'), 'skill_templates', ['client_id'], unique=False)
    op.create_table('squads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PROVISIONING', 'ACTIVE', 'PAUSED', 'ARCHIVED', name='squad_status_enum'), nullable=False),
    sa.Column('current_manifest_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_squads_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_manifest_id'], ['manifests.id'], name=op.f('fk_squads_current_manifest_id_manifests'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squads')),
    sa.UniqueConstraint('client_id', 'slug', name='uq_squad_client_slug')
    )
    op.create_index(op.f('ix_squads_client_id'), 'squads', ['client_id'], unique=False)
    op.create_table('agent_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('skill_template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain_business', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('IDLE', 'BUSY', 'PAUSED', 'DISABLED', name='agent_instance_status_enum'), nullable=False),
    sa.Column('config_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_agent_instances_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_template_id'], ['skill_templates.id'], name=op.f('fk_agent_instances_skill_template_id_skill_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_agent_instances_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_instances'))
    )
    op.create_index(op.f('ix_agent_instances_client_id'), 'agent_instances', ['client_id'], unique=False)
    op.create_index(op.f('ix_agent_instances_squad_id'), 'agent_instances', ['squad_id'], unique=False)
    op.create_table('knowledge_indexing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_knowledge_indexing_jobs_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_knowledge_indexing_jobs_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_indexing_jobs'))
    )
    op.create_index(op.f('ix_knowledge_indexing_jobs_client_id'), 'knowledge_indexing_jobs', ['client_id'], unique=False)
    op.create_index(op.f('ix_knowledge_indexing_jobs_squad_id'), 'knowledge_indexing_jobs', ['squad_id'], unique=False)
    op.create_table('manifests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_manifests_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_manifests_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_manifests_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manifests')),
    sa.UniqueConstraint('squad_id', 'version', name='uq_manifest_squad_version')
    )
    op.create_index(op.f('ix_manifests_client_id'), 'manifests', ['client_id'], unique=False)
    op.create_index(op.f('ix_manifests_squad_id'), 'manifests', ['squad_id'], unique=False)
    op.create_table('onboarding_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('repos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_per_stage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('interview_jira_issue_key', sa.String(length=64), nullable=True),
    sa.Column('calibration_score_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_onboarding_runs_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_onboarding_runs_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_runs'))
    )
    op.create_index(op.f('ix_onboarding_runs_client_id'), 'onboarding_runs', ['client_id'], unique=False)
    op.create_index(op.f('ix_onboarding_runs_squad_id'), 'onboarding_runs', ['squad_id'], unique=False)
    op.create_table('playbook_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=False),
    sa.Column('scope_glob', sa.String(length=255), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('example_code', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_vector_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_playbook_entries_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_playbook_entries_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_playbook_entries_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playbook_entries'))
    )
    op.create_index(op.f('ix_playbook_entries_client_id'), 'playbook_entries', ['client_id'], unique=False)
    op.create_index(op.f('ix_playbook_entries_squad_id'), 'playbook_entries', ['squad_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('squad_id', sa.UUID(), nullable=True),
    sa.Column('jira_workspace_url', sa.String(length=255), nullable=False),
    sa.Column('jira_issue_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('demand_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ba_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('architect_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_stage', sa.Enum('DEMAND_RECEIVED', 'BA_REFINING', 'BA_SPEC_AWAITING_APPROVAL', 'ARCHITECT_PLANNING', 'PLAN_AWAITING_APPROVAL', 'DEV_EXECUTING', 'PR_OPENED', 'HUMAN_REVIEW', 'MERGED', 'CANCELLED', 'FAILED', name='task_stage_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'CANCELLED', 'FAILED', name='task_status_enum'), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agent_instances.id'], name=op.f('fk_tasks_assigned_agent_id_agent_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_tasks_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], name=op.f('fk_tasks_parent_task_id_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_tasks_squad_id_squads'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('jira_workspace_url', 'jira_issue_key', name='uq_task_jira_external_id')
    )
    op.create_index(op.f('ix_tasks_client_id'), 'tasks', ['client_id'], unique=False)
    op.create_index(op.f('ix_tasks_squad_id'), 'tasks', ['squad_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('from_agent_id', sa.UUID(), nullable=True),
    sa.Column('to_agent_id', sa.UUID(), nullable=True),
    sa.Column('message_kind', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_agent_messages_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agent_instances.id'], name=op.f('fk_agent_messages_from_agent_id_agent_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_agent_messages_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agent_instances.id'], name=op.f('fk_agent_messages_to_agent_id_agent_instances'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_messages'))
    )
    op.create_index(op.f('ix_agent_messages_client_id'), 'agent_messages', ['client_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_task_id'), 'agent_messages', ['task_id'], unique=False)
    op.create_table('claude_api_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('agent_instance_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_instance_id'], ['agent_instances.id'], name=op.f('fk_claude_api_calls_agent_instance_id_agent_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_claude_api_calls_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_claude_api_calls_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claude_api_calls'))
    )
    op.create_index(op.f('ix_claude_api_calls_client_id'), 'claude_api_calls', ['client_id'], unique=False)
    op.create_index(op.f('ix_claude_api_calls_task_id'), 'claude_api_calls', ['task_id'], unique=False)
    op.create_table('cross_squad_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_client_id', sa.UUID(), nullable=False),
    sa.Column('source_squad_id', sa.UUID(), nullable=False),
    sa.Column('target_client_id', sa.UUID(), nullable=False),
    sa.Column('target_squad_id', sa.UUID(), nullable=False),
    sa.Column('requesting_task_id', sa.UUID(), nullable=False),
    sa.Column('need_description', sa.String(length=2048), nullable=False),
    sa.Column('proposed_contract', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_cross_squad_requests_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requesting_task_id'], ['tasks.id'], name=op.f('fk_cross_squad_requests_requesting_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_client_id'], ['clients.id'], name=op.f('fk_cross_squad_requests_source_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_squad_id'], ['squads.id'], name=op.f('fk_cross_squad_requests_source_squad_id_squads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_client_id'], ['clients.id'], name=op.f('fk_cross_squad_requests_target_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_squad_id'], ['squads.id'], name=op.f('fk_cross_squad_requests_target_squad_id_squads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cross_squad_requests'))
    )
    op.create_index(op.f('ix_cross_squad_requests_source_client_id'), 'cross_squad_requests', ['source_client_id'], unique=False)
    op.create_index(op.f('ix_cross_squad_requests_target_client_id'), 'cross_squad_requests', ['target_client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cross_squad_requests_target_client_id'), table_name='cross_squad_requests')
    op.drop_index(op.f('ix_cross_squad_requests_source_client_id'), table_name='cross_squad_requests')
    op.drop_table('cross_squad_requests')
    op.drop_index(op.f('ix_claude_api_calls_task_id'), table_name='claude_api_calls')
    op.drop_index(op.f('ix_claude_api_calls_client_id'), table_name='claude_api_calls')
    op.drop_table('claude_api_calls')
    op.drop_index(op.f('ix_agent_messages_task_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_client_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_tasks_squad_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_client_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_playbook_entries_squad_id'), table_name='playbook_entries')
    op.drop_index(op.f('ix_playbook_entries_client_id'), table_name='playbook_entries')
    op.drop_table('playbook_entries')
    op.drop_index(op.f('ix_onboarding_runs_squad_id'), table_name='onboarding_runs')
    op.drop_index(op.f('ix_onboarding_runs_client_id'), table_name='onboarding_runs')
    op.drop_table('onboarding_runs')
    op.drop_index(op.f('ix_manifests_squad_id'), table_name='manifests')
    op.drop_index(op.f('ix_manifests_client_id'), table_name='manifests')
    op.drop_table('manifests')
    op.drop_index(op.f('ix_knowledge_indexing_jobs_squad_id'), table_name='knowledge_indexing_jobs')
    op.drop_index(op.f('ix_knowledge_indexing_jobs_client_id'), table_name='knowledge_indexing_jobs')
    op.drop_table('knowledge_indexing_jobs')
    op.drop_index(op.f('ix_agent_instances_squad_id'), table_name='agent_instances')
    op.drop_index(op.f('ix_agent_instances_client_id'), table_name='agent_instances')
    op.drop_table('agent_instances')
    op.drop_index(op.f('ix_squads_client_id'), table_name='squads')
    op.drop_table('squads')
    op.drop_index(op.f('ix_skill_templates_client_id'), table_name='skill_templates')
    op.drop_table('skill_templates')
    op.drop_index(op.f('ix_encrypted_secrets_client_id'), table_name='encrypted_secrets')
    op.drop_table('encrypted_secrets')
    op.drop_index(op.f('ix_client_memberships_user_id'), table_name='client_memberships')
    op.drop_index(op.f('ix_client_memberships_client_id'), table_name='client_memberships')
    op.drop_table('client_memberships')
    op.drop_table('client_billing_plans')
    op.drop_index(op.f('ix_billing_periods_client_id'), table_name='billing_periods')
    op.drop_table('billing_periods')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_slug'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
