"""unify external api calls + billing overhead

Revision ID: 4378ec26485b
Revises: 188ba8eb067d
Create Date: 2026-05-13 08:49:38.349993

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4378ec26485b'
down_revision: str | Sequence[str] | None = '188ba8eb067d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_api_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('agent_instance_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('ANTHROPIC', 'VOYAGE', 'OPENAI', 'GITHUB', 'JIRA', 'OTHER', name='api_provider_enum'), nullable=False),
    sa.Column('kind', sa.Enum('CHAT', 'EMBEDDING', 'TOOL', 'WEBHOOK', 'OTHER', name='api_call_kind_enum'), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_input_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_instance_id'], ['agent_instances.id'], name=op.f('fk_external_api_calls_agent_instance_id_agent_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_external_api_calls_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_external_api_calls_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_api_calls'))
    )
    op.create_index(op.f('ix_external_api_calls_client_id'), 'external_api_calls', ['client_id'], unique=False)
    op.create_index(op.f('ix_external_api_calls_kind'), 'external_api_calls', ['kind'], unique=False)
    op.create_index(op.f('ix_external_api_calls_provider'), 'external_api_calls', ['provider'], unique=False)
    op.create_index(op.f('ix_external_api_calls_task_id'), 'external_api_calls', ['task_id'], unique=False)
    op.drop_index(op.f('ix_claude_api_calls_client_id'), table_name='claude_api_calls')
    op.drop_index(op.f('ix_claude_api_calls_task_id'), table_name='claude_api_calls')
    op.drop_table('claude_api_calls')
    op.add_column('billing_periods', sa.Column('total_cost_direct_usd', sa.Numeric(precision=12, scale=6), nullable=False, server_default='0'))
    op.add_column('billing_periods', sa.Column('total_cost_direct_brl', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('billing_periods', sa.Column('total_cost_infra_brl', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('billing_periods', sa.Column('total_cost_fixed_brl', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('billing_periods', sa.Column('total_cost_full_brl', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.drop_column('billing_periods', 'total_cost_usd')
    op.add_column('client_billing_plans', sa.Column('infra_overhead_pct', sa.Numeric(precision=6, scale=2), nullable=False, server_default='20'))
    op.add_column('client_billing_plans', sa.Column('fixed_overhead_brl_per_task', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('client_billing_plans', sa.Column('usd_to_brl_rate', sa.Numeric(precision=10, scale=4), nullable=False, server_default='5.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_billing_plans', 'usd_to_brl_rate')
    op.drop_column('client_billing_plans', 'fixed_overhead_brl_per_task')
    op.drop_column('client_billing_plans', 'infra_overhead_pct')
    op.add_column('billing_periods', sa.Column('total_cost_usd', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=False))
    op.drop_column('billing_periods', 'total_cost_full_brl')
    op.drop_column('billing_periods', 'total_cost_fixed_brl')
    op.drop_column('billing_periods', 'total_cost_infra_brl')
    op.drop_column('billing_periods', 'total_cost_direct_brl')
    op.drop_column('billing_periods', 'total_cost_direct_usd')
    op.create_table('claude_api_calls',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('agent_instance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('input_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('output_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cache_creation_input_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cache_read_input_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost_usd', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=False),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_instance_id'], ['agent_instances.id'], name=op.f('fk_claude_api_calls_agent_instance_id_agent_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_claude_api_calls_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_claude_api_calls_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claude_api_calls'))
    )
    op.create_index(op.f('ix_claude_api_calls_task_id'), 'claude_api_calls', ['task_id'], unique=False)
    op.create_index(op.f('ix_claude_api_calls_client_id'), 'claude_api_calls', ['client_id'], unique=False)
    op.drop_index(op.f('ix_external_api_calls_task_id'), table_name='external_api_calls')
    op.drop_index(op.f('ix_external_api_calls_provider'), table_name='external_api_calls')
    op.drop_index(op.f('ix_external_api_calls_kind'), table_name='external_api_calls')
    op.drop_index(op.f('ix_external_api_calls_client_id'), table_name='external_api_calls')
    op.drop_table('external_api_calls')
    # ### end Alembic commands ###
